language: csharp  
solution: Lab1.sln
mono: none
dotnet: 2.1.300
services:
  - docker
before_script:
  - dotnet restore
  - docker-compose build
  - docker-compose run notes bundle exec rails db:test:prepare
script:
  - dotnet test ./Tests/Tests.csproj
  - docker-compose run --rm notes bundle exec rake spec