language: csharp  
solution: Lab1.sln
mono: latest
sudo: false 
dotnet: 2.1.300
install:
  - dotnet restore
script:    # the following commands are just examples, use whatever your build process requires
  - dotnet test ./tests/tests.csproj -f netcoreapp2.1