language: csharp  
sudo: required 
solution: Lab1.sln
dist: trusty  
mono: none
dotnet: dotnet-sdk-2.1
before_script:
  - dotnet restore
script:    # the following commands are just examples, use whatever your build process requires
  - ./build.sh